# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Mytest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: My Test
      runs-on: ubuntu-latest
      steps:
      - name: Print a greeting
      run:
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
